pipeline {
    agent any
    tools {
        maven "M3"
        jdk "java8"
    }

    environment {
        app_name = 'jarvis-trading-app'
    }

    stages {
        stage('artifactory setup') {
            steps {
                rtServer(
                  id: 'Artifactory',
                  url: 'artifactory:8081/artifactory/trading-app-repo',
                  credentialsId: 'jenkins-artifactory',
                )

                rtMavenDeployer(
                  id: 'MAVEN_DEPLOYER',
                  serverId: 'Artifactory',
                  releaseRepo: 'trading-app-repo',
                  snapshotRepo: 'trading-app-repo',
                )
            }
        }
        stage('build-master') {
            when { branch 'master' }
            steps {

            }
        }
        stage('build-dev') {
            when { branch 'develop' }
            steps {
                rtMavenRun(
                    tool: M3,
                    pom: 'springboot/pom.xml',
                    goals: 'clean install',
                    deployerId: 'MAVEN_DEPLOYER',
                )
            }
        }

    }
}
