pipeline {
    agent any
    tools {
        maven "M3"
        jdk "java8"
    }

    environment {
        app_name = 'jarvis-trading-app'
    }

    stages {
        stage('Build') {
            steps {
                sh 'cd springboot && mvn clean package -DskipTests'
                echo "App name is ${env.app_name}"
                archiveArtifacts 'springboot/target/*jar'
            }
        }
        stage('Deploy_dev') {
            steps {
                echo "Current branch is ${env.GIT_BRANCH}"
                sh "bash ./springboot/scripts/eb/eb_deploy.sh ${app_name} JarvisTradingApp-development"
            }
        }
        stage('Deploy_prod') {
            steps {
                echo "Current branch is ${env.GIT_BRANCH}"
                sh "bash ./springboot/scripts/eb/eb_deploy.sh ${app_name} JarvisTradingApp-prod"
            }
        }
    }
}
